services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    env_file:
      - src/main/resources/env.properties
    ports:
      - "8080:8080"
    network_mode: host

  app-qa:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app-qa
    restart: unless-stopped
    env_file:
      - src/main/resources/env.properties
    ports:
      - "8082:8082"
    network_mode: host

  postgres:
    build:
      context: docker/pgsql
      dockerfile: Dockerfile
    container_name: postgres
    restart: unless-stopped
    env_file:
      - docker/pgsql/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: "1g"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - docker/redis/.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-qa:
    image: redis:7.4-alpine
    container_name: redis-qa
    restart: unless-stopped
    env_file:
      - docker/redis/.env
    ports:
      - "6380:6379"
    volumes:
      - redis_qa_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - POSTGRES_USER=${HARUUP_USER:-haruup_user}
      - POSTGRES_PASSWORD=${HARUUP_USER_PASSWORD:-haruup@001}
      - POSTGRES_HOST=${POSTGRES_HOST:-host.docker.internal}
      - POSTGRES_DB=${HARUUP_DB:-haruup}
    env_file:
      - docker/pgsql/.env
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  postgres_data:
  redis_data:
  redis_qa_data:
  loki_data:
