global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        # 만약 Linux 환경에서 host.docker.internal 이 안되면
        # 여기를 실제 호스트 IP:8080 으로 바꿔주면 됨. 예: ["172.17.0.1:8080"]
